/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaz;

import estructuras.matrices.dispersa.cabeceras.ListaCabeceras;
import estructuras.matrices.dispersa.laterales.ListaHorizontal;
import estructuras.matrices.dispersa.laterales.ListaLaterales;
import estructuras.matrices.dispersa.cabeceras.ListaVertical;
import estructuras.matrices.dispersa.Matriz;
import estructuras.matrices.dispersa.cabeceras.NodoCabecera;
import estructuras.matrices.dispersa.laterales.NodoLateral;
import estructuras.matrices.dispersa.NodoOrtogonal;
import java.io.IOException;

/**
 *
 * @author g
 */
public class VentanaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form VentanaPrincipal
     */
    public VentanaPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        bienvenido_lb = new javax.swing.JLabel();
        info_lb = new javax.swing.JLabel();
        visualizar_btn = new javax.swing.JButton();
        estado_memoria_titulo_lb = new javax.swing.JLabel();
        visualizacion_titulo_lb = new javax.swing.JLabel();
        abrir_btn = new javax.swing.JButton();
        archivo_carga_cb = new javax.swing.JComboBox<>();
        modo_visualizar_cb = new javax.swing.JComboBox<>();
        carga_info_lb = new javax.swing.JLabel();
        visualizar_info_lb = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        archivo_menu = new javax.swing.JMenu();
        carga_sub_menu = new javax.swing.JMenu();
        carga_capas_memoria_menu_item = new javax.swing.JMenuItem();
        carga_imagenes_menu_item = new javax.swing.JMenuItem();
        carga_usuarios_menu_item = new javax.swing.JMenuItem();
        salir_menu_item = new javax.swing.JMenuItem();
        editar_menu = new javax.swing.JMenu();
        usuarios_menu_item = new javax.swing.JMenuItem();
        imagenes_menu_item = new javax.swing.JMenuItem();
        ayuda_menu = new javax.swing.JMenu();
        m_usuario_menu_item = new javax.swing.JMenuItem();
        m_tecnico_menu_item = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Proyecto 1 - Generador de imagenes por capas");

        bienvenido_lb.setFont(new java.awt.Font("Ubuntu", 0, 36)); // NOI18N
        bienvenido_lb.setText("¡Bienvenido!");

        info_lb.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        info_lb.setText("Selecciona la acción que deseas realizar.");

        visualizar_btn.setText("Visualizar");
        visualizar_btn.setActionCommand("");
        visualizar_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                visualizar_btnActionPerformed(evt);
            }
        });

        estado_memoria_titulo_lb.setFont(new java.awt.Font("Ubuntu", 0, 24)); // NOI18N
        estado_memoria_titulo_lb.setText("Estado de la memoria");

        visualizacion_titulo_lb.setFont(new java.awt.Font("Ubuntu", 0, 24)); // NOI18N
        visualizacion_titulo_lb.setText("Visualización de imagenes");

        abrir_btn.setText("Abrir");

        archivo_carga_cb.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Lista de imagenes", "Árbol de capas", "Capa", "Imagen y árbol de capas", "Árbol de usuarios" }));

        modo_visualizar_cb.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Recorrido limitado", "Lista de imagenes", "Capa", "Usuario" }));
        modo_visualizar_cb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modo_visualizar_cbActionPerformed(evt);
            }
        });

        carga_info_lb.setText("Elige lo que deseas ver.");

        visualizar_info_lb.setText("Elige la forma en que deseas visualizar.");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(bienvenido_lb)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(archivo_carga_cb, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(carga_info_lb, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(estado_memoria_titulo_lb))
                        .addGap(98, 98, 98)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(visualizacion_titulo_lb)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(visualizar_info_lb, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(modo_visualizar_cb, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(visualizar_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(abrir_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(113, 113, 113))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(info_lb)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(bienvenido_lb)
                .addGap(18, 18, 18)
                .addComponent(info_lb)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(estado_memoria_titulo_lb, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(visualizacion_titulo_lb, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(carga_info_lb)
                    .addComponent(visualizar_info_lb))
                .addGap(14, 14, 14)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(modo_visualizar_cb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(archivo_carga_cb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(45, 45, 45)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(visualizar_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(abrir_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        archivo_menu.setText("Archivo");

        carga_sub_menu.setText("Cargar");

        carga_capas_memoria_menu_item.setText("Capas");
        carga_sub_menu.add(carga_capas_memoria_menu_item);

        carga_imagenes_menu_item.setText("Imagenes");
        carga_sub_menu.add(carga_imagenes_menu_item);

        carga_usuarios_menu_item.setText("Usuarios");
        carga_sub_menu.add(carga_usuarios_menu_item);

        archivo_menu.add(carga_sub_menu);

        salir_menu_item.setText("Salir");
        salir_menu_item.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salir_menu_itemActionPerformed(evt);
            }
        });
        archivo_menu.add(salir_menu_item);

        jMenuBar1.add(archivo_menu);

        editar_menu.setText("Editar");

        usuarios_menu_item.setText("Gestionar usuarios");
        editar_menu.add(usuarios_menu_item);

        imagenes_menu_item.setText("Gestonar imagenes");
        editar_menu.add(imagenes_menu_item);

        jMenuBar1.add(editar_menu);

        ayuda_menu.setText("Ayuda");

        m_usuario_menu_item.setText("Manual de usuario");
        ayuda_menu.add(m_usuario_menu_item);

        m_tecnico_menu_item.setText("Manual tecnico");
        m_tecnico_menu_item.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                m_tecnico_menu_itemActionPerformed(evt);
            }
        });
        ayuda_menu.add(m_tecnico_menu_item);

        jMenuBar1.add(ayuda_menu);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void salir_menu_itemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salir_menu_itemActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_salir_menu_itemActionPerformed

    private void m_tecnico_menu_itemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_m_tecnico_menu_itemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_m_tecnico_menu_itemActionPerformed

    private void modo_visualizar_cbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modo_visualizar_cbActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_modo_visualizar_cbActionPerformed

    private void visualizar_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_visualizar_btnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_visualizar_btnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) throws IOException {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        // ||||||||||||||||||||||||     Test    ||||||||||||||||||||||||
        // ................ Listas de matriz ...................
//            System.out.println("Lista vertical");
//            ListaVertical lv = new ListaVertical();
//            lv.insertar(new NodoOrtogonal("1", 0, 0));
//            lv.insertar(new NodoOrtogonal("1", 0, 3));
//            lv.insertar(new NodoOrtogonal("1", 0, 1));
//            lv.insertar(new NodoOrtogonal("1", 0, 5));
//            lv.insertar(new NodoOrtogonal("1", 0, 2));
//
//            lv.mostrar();
//            System.out.println("Lista Horizontal");
//            ListaHorizontal lh = new ListaHorizontal();
//            lh.insertar(new NodoOrtogonal("1", 5, 0));
//            lh.insertar(new NodoOrtogonal("1", 3, 3));
//            lh.insertar(new NodoOrtogonal("1", 4, 1));
//            lh.insertar(new NodoOrtogonal("1", 1, 5));
//            lh.insertar(new NodoOrtogonal("1", 0, 2));
//
//            lh.mostrar();

//            System.out.println("Lista cabeceras");
//            ListaCabeceras lcab = new ListaCabeceras();
//            lcab.insertar(new NodoCabecera(3));
//            lcab.insertar(new NodoCabecera(0));
//            lcab.insertar(new NodoCabecera(1));
//            lcab.insertar(new NodoCabecera(5));
//            lcab.insertar(new NodoCabecera(4));
//            
//            lcab.mostrar();
//            NodoCabecera m = lcab.buscar(1);
//            System.out.println("Nodo m: " + m.getX());
//
//            System.out.println("Lista laterales");
//            ListaLaterales llat = new ListaLaterales();
//            llat.insertar(new NodoLateral(6));
//            llat.insertar(new NodoLateral(7));
//            llat.insertar(new NodoLateral(2));
//            llat.insertar(new NodoLateral(4));
//            llat.insertar(new NodoLateral(0));
//            llat.insertar(new NodoLateral(1));
//            
//            llat.mostrar();
//            NodoLateral n  = llat.buscar(100);
//            System.out.println("Nodo n: " + n.getY());
        Matriz matriz = new Matriz();
//        matriz.llenar(3, 3);
        matriz.insertar(0, 0, "#32CD32");
        matriz.insertar(0, 1, "#32CD35");
        matriz.insertar(0, 2, "#32CD42");
        matriz.insertar(1, 1, "#32CD32");
        matriz.insertar(2, 2, "#32CD32");
        
//        String dato = matriz.laterales.buscar(0).getFilas().primero.getAbajo().getDerecha().getColor();
        matriz.graficar("grafo", "1");
            
//        System.out.println(dato);
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton abrir_btn;
    private javax.swing.JComboBox<String> archivo_carga_cb;
    private javax.swing.JMenu archivo_menu;
    private javax.swing.JMenu ayuda_menu;
    private javax.swing.JLabel bienvenido_lb;
    private javax.swing.JMenuItem carga_capas_memoria_menu_item;
    private javax.swing.JMenuItem carga_imagenes_menu_item;
    private javax.swing.JLabel carga_info_lb;
    private javax.swing.JMenu carga_sub_menu;
    private javax.swing.JMenuItem carga_usuarios_menu_item;
    private javax.swing.JMenu editar_menu;
    private javax.swing.JLabel estado_memoria_titulo_lb;
    private javax.swing.JMenuItem imagenes_menu_item;
    private javax.swing.JLabel info_lb;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JMenuItem m_tecnico_menu_item;
    private javax.swing.JMenuItem m_usuario_menu_item;
    private javax.swing.JComboBox<String> modo_visualizar_cb;
    private javax.swing.JMenuItem salir_menu_item;
    private javax.swing.JMenuItem usuarios_menu_item;
    private javax.swing.JLabel visualizacion_titulo_lb;
    private javax.swing.JButton visualizar_btn;
    private javax.swing.JLabel visualizar_info_lb;
    // End of variables declaration//GEN-END:variables
}
